# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            IndyVal
tagline:          'Indy's Valuations'
description:      'Welcome to my blog'
url:              http://www.indyval.com

author:
  name:           'Indy'
  url:            http://www.indyval.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/inderbir/inderbir.github.io
