# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
auto:                true
permalink:           pretty
relative_permalinks: true

# Setup
title:               IndyVal
tagline:             'Indys Valuations'
description:         'Welcome to my blog'
url:                 http://www.indyval.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Indy Bal
  url:               https://twitter.com/ 
  email:             inderbirbal@gmail.com

# Custom vars
version:             1.0.0